// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v1/uid_generator.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UIDGenerator_GenerateUID_FullMethodName = "/uid_generator.UIDGenerator/GenerateUID"
)

// UIDGeneratorClient is the client API for UIDGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UIDGeneratorClient interface {
	GenerateUID(ctx context.Context, in *GenerateUIDReq, opts ...grpc.CallOption) (*GenerateUIDResp, error)
}

type uIDGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewUIDGeneratorClient(cc grpc.ClientConnInterface) UIDGeneratorClient {
	return &uIDGeneratorClient{cc}
}

func (c *uIDGeneratorClient) GenerateUID(ctx context.Context, in *GenerateUIDReq, opts ...grpc.CallOption) (*GenerateUIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateUIDResp)
	err := c.cc.Invoke(ctx, UIDGenerator_GenerateUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UIDGeneratorServer is the server API for UIDGenerator service.
// All implementations must embed UnimplementedUIDGeneratorServer
// for forward compatibility.
type UIDGeneratorServer interface {
	GenerateUID(context.Context, *GenerateUIDReq) (*GenerateUIDResp, error)
	mustEmbedUnimplementedUIDGeneratorServer()
}

// UnimplementedUIDGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUIDGeneratorServer struct{}

func (UnimplementedUIDGeneratorServer) GenerateUID(context.Context, *GenerateUIDReq) (*GenerateUIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUID not implemented")
}
func (UnimplementedUIDGeneratorServer) mustEmbedUnimplementedUIDGeneratorServer() {}
func (UnimplementedUIDGeneratorServer) testEmbeddedByValue()                      {}

// UnsafeUIDGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UIDGeneratorServer will
// result in compilation errors.
type UnsafeUIDGeneratorServer interface {
	mustEmbedUnimplementedUIDGeneratorServer()
}

func RegisterUIDGeneratorServer(s grpc.ServiceRegistrar, srv UIDGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedUIDGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UIDGenerator_ServiceDesc, srv)
}

func _UIDGenerator_GenerateUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIDGeneratorServer).GenerateUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIDGenerator_GenerateUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIDGeneratorServer).GenerateUID(ctx, req.(*GenerateUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UIDGenerator_ServiceDesc is the grpc.ServiceDesc for UIDGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UIDGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uid_generator.UIDGenerator",
	HandlerType: (*UIDGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateUID",
			Handler:    _UIDGenerator_GenerateUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/uid_generator.proto",
}
