// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/uid_generator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcquireUIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireUIDReq) Reset() {
	*x = AcquireUIDReq{}
	mi := &file_v1_uid_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireUIDReq) ProtoMessage() {}

func (x *AcquireUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_uid_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireUIDReq.ProtoReflect.Descriptor instead.
func (*AcquireUIDReq) Descriptor() ([]byte, []int) {
	return file_v1_uid_generator_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireUIDReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type AcquireUIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireUIDResp) Reset() {
	*x = AcquireUIDResp{}
	mi := &file_v1_uid_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireUIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireUIDResp) ProtoMessage() {}

func (x *AcquireUIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_uid_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireUIDResp.ProtoReflect.Descriptor instead.
func (*AcquireUIDResp) Descriptor() ([]byte, []int) {
	return file_v1_uid_generator_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireUIDResp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_v1_uid_generator_proto protoreflect.FileDescriptor

const file_v1_uid_generator_proto_rawDesc = "" +
	"\n" +
	"\x16v1/uid_generator.proto\x12\ruid_generator\",\n" +
	"\rAcquireUIDReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\"\n" +
	"\x0eAcquireUIDResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid2Y\n" +
	"\fUIDGenerator\x12I\n" +
	"\n" +
	"AcquireUID\x12\x1c.uid_generator.AcquireUIDReq\x1a\x1d.uid_generator.AcquireUIDRespB\x06Z\x04.;v1b\x06proto3"

var (
	file_v1_uid_generator_proto_rawDescOnce sync.Once
	file_v1_uid_generator_proto_rawDescData []byte
)

func file_v1_uid_generator_proto_rawDescGZIP() []byte {
	file_v1_uid_generator_proto_rawDescOnce.Do(func() {
		file_v1_uid_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_uid_generator_proto_rawDesc), len(file_v1_uid_generator_proto_rawDesc)))
	})
	return file_v1_uid_generator_proto_rawDescData
}

var file_v1_uid_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_uid_generator_proto_goTypes = []any{
	(*AcquireUIDReq)(nil),  // 0: uid_generator.AcquireUIDReq
	(*AcquireUIDResp)(nil), // 1: uid_generator.AcquireUIDResp
}
var file_v1_uid_generator_proto_depIdxs = []int32{
	0, // 0: uid_generator.UIDGenerator.AcquireUID:input_type -> uid_generator.AcquireUIDReq
	1, // 1: uid_generator.UIDGenerator.AcquireUID:output_type -> uid_generator.AcquireUIDResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_uid_generator_proto_init() }
func file_v1_uid_generator_proto_init() {
	if File_v1_uid_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_uid_generator_proto_rawDesc), len(file_v1_uid_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_uid_generator_proto_goTypes,
		DependencyIndexes: file_v1_uid_generator_proto_depIdxs,
		MessageInfos:      file_v1_uid_generator_proto_msgTypes,
	}.Build()
	File_v1_uid_generator_proto = out.File
	file_v1_uid_generator_proto_goTypes = nil
	file_v1_uid_generator_proto_depIdxs = nil
}
